# PersistentVolumeClaim for ZooKeeper data
# Note: Solr PVCs are automatically created by the StatefulSet
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-data
  namespace: solr-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
