apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solrcloud
  namespace: solr-namespace
  labels:
    app: solrcloud
spec:
  serviceName: solrcloud-headless
  replicas: 2
  selector:
    matchLabels:
      app: solrcloud
  template:
    metadata:
      labels:
        app: solrcloud
    spec:
      # Init container to fix volume permissions
      # Solr runs as user 8983:8983 but hostPath volumes are owned by root
      initContainers:
      - name: fix-permissions
        image: busybox:latest
        command: ['sh', '-c', 'chown -R 8983:8983 /var/solr && chmod -R 755 /var/solr']
        volumeMounts:
        - name: solr-data
          mountPath: /var/solr
        securityContext:
          runAsUser: 0  # Run as root to fix permissions
      containers:
      - name: solr
        image: solr:9.7
        ports:
        - containerPort: 8983
          name: solr-port
        env:
        - name: ZK_HOST
          value: "zookeeper:2181"
        - name: SOLR_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SOLR_JAVA_MEM
          value: "-Xms2g -Xmx2g"
        args:
        - "solr-foreground"
        - "-c"
        - "-z"
        - "zookeeper:2181"
        volumeMounts:
        - name: solr-data
          mountPath: /var/solr
        resources:
          requests:
            memory: "6Gi"
            cpu: "1000m"
          limits:
            memory: "6Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /solr/admin/info/system
            port: 8983
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /solr/admin/info/system
            port: 8983
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
  # VolumeClaimTemplates automatically create a PVC for each pod
  volumeClaimTemplates:
  - metadata:
      name: solr-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: solrcloud
  namespace: solr-namespace
  labels:
    app: solrcloud
spec:
  ports:
  - port: 8983
    targetPort: 8983
    name: solr-port
  selector:
    app: solrcloud
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: solrcloud-headless
  namespace: solr-namespace
  labels:
    app: solrcloud
spec:
  clusterIP: None
  ports:
  - port: 8983
    targetPort: 8983
    name: solr-port
  selector:
    app: solrcloud
